### ISSUE TITLE
E5M2 or mix format trial

### ISSUE THREAD

**Issue by zitgit** [neuralmagic/AutoFP8#26]
@mgoin Hi! Have u tried e5m2 quant or mix format quant such as e4m3 for weight and e5m2 for activation?

**Comment by zitgit** [comment]
![image](https://github.com/neuralmagic/AutoFP8/assets/42319139/f6362942-309c-49c6-bb54-6d0102d9675a)
I changed the quantize method to torch_e5m2 for testing accuracy. The outputs were totally wrong.

**Comment by mgoin** [comment]
e5m2 loses too much precision generally. This is why e4m3 with a well-tuned scale is better in most cases
