### ISSUE TITLE
I get empty response after Quantizing LLama2 70B using AutoFP8 with calibration

### ISSUE THREAD

**Issue by e3oroush** [neuralmagic/AutoFP8#27]
I'm trying to quantize llama2 70B using [AutoFP8 with calibration samples from ultrachat](https://github.com/neuralmagic/AutoFP8/blob/147fa4d9e1a90ef8a93f96fc7d9c33056ddc017a/example_dataset.py) in a DGX with H100 and cuda12.2

The model is successfully, however, in loading it on vllm, the generated token's response is always empty. The logs show it's generating something, but it doesn't return anything.
```python
>>> vllm.__version__
'0.5.0.post1'
>>> requests.post("http://localhost:8080/v1/chat/completions",json={"messages":[{"content":"what is ai","role":"user"}], "model": "llama", "max_tokens": 200}).json()
{'id': 'cmpl-fc71adce4bc64df5b215b3051d1c698c',
 'object': 'chat.completion',
 'created': 1720516050,
 'model': 'llama',
 'choices': [{'index': 0,
   'message': {'role': 'assistant', 'content': '', 'tool_calls': []},
   'logprobs': None,
   'finish_reason': 'length',
   'stop_reason': None}],
 'usage': {'prompt_tokens': 11, 'total_tokens': 211, 'completion_tokens': 200}}

```
And here is the command I use to start the server:
```bash
python3 -m vllm.entrypoints.openai.api_server --model ./Meta-Llama-2-70B-hf-FP8-KV  --port 8080 --served-model-name llama --kv-cache-dtype fp8
```

Any hints would be appreciated.

**Comment by mgoin** [comment]
Can you share the full code you used here to produce the model and/or the checkpoint? Do you get the same result without specifying `--kv-cache-dtype fp8`?

We have an accurate llama 2 7B checkpoint without kv cache quant: https://huggingface.co/neuralmagic/Llama-2-7b-chat-hf-FP8

**Comment by e3oroush** [comment]
Thanks for your response.  
I used the exact same code for llama3-70B just changed the model. Here's the code:
```python
from datasets import load_dataset
from transformers import AutoTokenizer

from auto_fp8 import AutoFP8ForCausalLM, BaseQuantizeConfig

pretrained_model_dir = "meta-llama/Llama-2-70b-hf"
quantized_model_dir = "Meta-Llama-2-70B-hf-FP8-KV"

tokenizer = AutoTokenizer.from_pretrained(pretrained_model_dir, use_fast=True)
tokenizer.pad_token = tokenizer.eos_token

ds = load_dataset("mgoin/ultrachat_2k", split="train_sft")
examples = [tokenizer.apply_chat_template(batch["messages"], tokenize=False) for batch in ds]
examples = tokenizer(examples, padding=True, truncation=True, return_tensors="pt").to("cuda")

quantize_config = BaseQuantizeConfig(
    quant_method="fp8",
    activation_scheme="static",
    ignore_patterns=["re:.*lm_head"],
    kv_cache_quant_targets=("k_proj", "v_proj"),
)

model = AutoFP8ForCausalLM.from_pretrained(pretrained_model_dir, quantize_config)
model.quantize(examples)
model.save_quantized(quantized_model_dir)
```

Yes I get the exact same response with or without `--kv-cache-dtype fp8`

**Comment by mgoin** [comment]
@e3oroush I think part of is the issue is that you are using a base model, not a chat-finetuned model. In your example you are both applying a chat template during calibration and in the openai-api. I think you want to start with https://huggingface.co/meta-llama/Llama-2-70b-chat-hf

**Comment by e3oroush** [comment]
You're right. But I was expecting it to generate none-sense, not to return empty string.  
I'll try to use `/generate` endpoint and let you know the result.

**Comment by mgoin** [comment]
@e3oroush could you try static activation scales without quantizing the kv cache i.e. `kv_cache_quant_targets=("k_proj", "v_proj"),`

**Comment by e3oroush** [comment]
I'll do it and get back to you with the results. Thanks.

**Comment by e3oroush** [comment]
So my guess was correct and it was because of its tokenizer. I made a small change on the script and set `max_length=4096` so the tokenizer knows how to truncate the sequences. Here's the final script worked for me:

```python
from datasets import load_dataset
from transformers import AutoTokenizer

from auto_fp8 import AutoFP8ForCausalLM, BaseQuantizeConfig

pretrained_model_dir = "meta-llama/Llama-2-70b-hf"
quantized_model_dir = "Meta-Llama-2-70B-hf-FP8-KV"

tokenizer = AutoTokenizer.from_pretrained(pretrained_model_dir, use_fast=False)
tokenizer.pad_token = tokenizer.eos_token

ds = load_dataset("mgoin/ultrachat_2k", split="train_sft")
examples = [tokenizer.apply_chat_template(batch["messages"], tokenize=False) for batch in ds]
examples = tokenizer(examples, padding=True, truncation=True, return_tensors="pt", max_length=4096).to("cuda")

quantize_config = BaseQuantizeConfig(
    quant_method="fp8",
    activation_scheme="static",
    ignore_patterns=["re:.*lm_head"],
    kv_cache_quant_targets=("k_proj", "v_proj"),
)

model = AutoFP8ForCausalLM.from_pretrained(pretrained_model_dir, quantize_config)
model.quantize(examples)
model.save_quantized(quantized_model_dir)
```
